global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files: [/data/targets/blackbox-icmp.json]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - target_label: probe_source
        replacement: testing
      - target_label: scrape_source
        replacement: testing

  - job_name: blackbox-tcp
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files: [/data/targets/blackbox-tcp.json]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
        replacement: ${1}:22
      - source_labels: [__address__, os]
        regex: (.*);windows
        target_label: __param_target
        replacement: ${1}:3389
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - target_label: probe_source
        replacement: testing
      - target_label: scrape_source
        replacement: testing

  - job_name: node-exporter
    file_sd_configs:
      - files: [/data/targets/testing-node.json]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: testing
      - target_label: scrape_source
        replacement: testing

  - job_name: libvirt-vm
    file_sd_configs:
      - files: [/data/targets/testing-libvirt.json]
    relabel_configs:
      - source_labels: [__address__]
        target_label: host_ip
      - source_labels: [__address__]
        target_label: __address__
        replacement: ${1}:9177
      - target_label: environment
        replacement: testing
      - target_label: scrape_source
        replacement: testing

  - job_name: self-monitoring
    static_configs:
      - targets:
          - 127.0.0.1:8429
        labels:
          component: vmagent
          environment: testing
          scrape_source: testing
      - targets:
          - 127.0.0.1:9115
        labels:
          component: blackbox-exporter
          environment: testing
          scrape_source: testing
      - targets:
          - 127.0.0.1:9100
        labels:
          component: node-exporter
          environment: testing
          scrape_source: testing
      - targets:
          - 127.0.0.1:9177
        labels:
          component: libvirt-exporter
          environment: testing
          scrape_source: testing
