---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: tooling
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: tooling
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: tooling
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app.kubernetes.io/part-of: cicd-lab
    example.com/env: prod